/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_reactivetoolbox_asyncio_IoUring */

#ifndef _Included_org_reactivetoolbox_asyncio_IoUring
#define _Included_org_reactivetoolbox_asyncio_IoUring
#ifdef __cplusplus
extern "C" {
#endif
#undef org_reactivetoolbox_asyncio_IoUring_DEFAULT_QUEUE_SIZE
#define org_reactivetoolbox_asyncio_IoUring_DEFAULT_QUEUE_SIZE 4096L
#undef org_reactivetoolbox_asyncio_IoUring_DEFAULT_FLAGS
#define org_reactivetoolbox_asyncio_IoUring_DEFAULT_FLAGS 0L
/*
 * Class:     org_reactivetoolbox_asyncio_IoUring
 * Method:    initIds
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_reactivetoolbox_asyncio_IoUring_initIds
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_reactivetoolbox_asyncio_IoUring
 * Method:    init
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_reactivetoolbox_asyncio_IoUring_init
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_reactivetoolbox_asyncio_IoUring
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_reactivetoolbox_asyncio_IoUring_exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
