/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_reactivetoolbox_asyncio_NativeIO */

#ifndef _Included_org_reactivetoolbox_asyncio_NativeIO
#define _Included_org_reactivetoolbox_asyncio_NativeIO
#ifdef __cplusplus
extern "C" {
#endif
#undef org_reactivetoolbox_asyncio_NativeIO_DEFAULT_QUEUE_SIZE
#define org_reactivetoolbox_asyncio_NativeIO_DEFAULT_QUEUE_SIZE 4096L
#undef org_reactivetoolbox_asyncio_NativeIO_DEFAULT_QUEUE_FLAGS
#define org_reactivetoolbox_asyncio_NativeIO_DEFAULT_QUEUE_FLAGS 0L
/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    initRing
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_initRing
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    closeRing
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_closeRing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    peekCQ
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_peekCQ
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    advanceCQ
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_advanceCQ
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    spaceLeft
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_spaceLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    submitAndWait
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_submitAndWait
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    prepareIO
 * Signature: (JIIJJJIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_prepareIO
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jlong, jlong, jint, jint, jlong);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    createSocket
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_createSocket
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    bind
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_bind
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_reactivetoolbox_asyncio_NativeIO
 * Method:    listen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_reactivetoolbox_asyncio_NativeIO_listen
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
