/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_reactivetoolbox_asyncio_IoUring */

#ifndef _Included_org_reactivetoolbox_asyncio_IoUring
#define _Included_org_reactivetoolbox_asyncio_IoUring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_reactivetoolbox_asyncio_IoUring
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_reactivetoolbox_asyncio_IoUring_initIds
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
